//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosMangaGods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosMangaGods() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RecursosMangaGods", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El autor se ha actualizado exitosamente.
        /// </summary>
        internal static string ConfirmacionActualizacionAutor {
            get {
                return ResourceManager.GetString("ConfirmacionActualizacionAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El género se ha actualizado exitosamente.
        /// </summary>
        internal static string ConfirmacionActualizacionGenero {
            get {
                return ResourceManager.GetString("ConfirmacionActualizacionGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El manga se ha actualizado exitosamente.
        /// </summary>
        internal static string ConfirmacionActualizacionManga {
            get {
                return ResourceManager.GetString("ConfirmacionActualizacionManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El autor se ha borrado exitosamente..
        /// </summary>
        internal static string ConfirmacionBorradoAutor {
            get {
                return ResourceManager.GetString("ConfirmacionBorradoAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El género se ha borrado exitosamente..
        /// </summary>
        internal static string ConfirmacionBorradoGenero {
            get {
                return ResourceManager.GetString("ConfirmacionBorradoGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El manga se ha borrado exitosamente.
        /// </summary>
        internal static string ConfirmacionBorradoManga {
            get {
                return ResourceManager.GetString("ConfirmacionBorradoManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El autor se ha creado exitosamente.
        /// </summary>
        internal static string ConfirmacionCreacionAutor {
            get {
                return ResourceManager.GetString("ConfirmacionCreacionAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El género de manga se ha creado exitosamente.
        /// </summary>
        internal static string ConfirmacionCreacionGenero {
            get {
                return ResourceManager.GetString("ConfirmacionCreacionGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El manga se ha creado exitosamente.
        /// </summary>
        internal static string ConfirmacionCreacionManga {
            get {
                return ResourceManager.GetString("ConfirmacionCreacionManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al actualizar los datos del autor..
        /// </summary>
        internal static string ErrorActualizarAutor {
            get {
                return ResourceManager.GetString("ErrorActualizarAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al intentar actualizar el carrito de compra..
        /// </summary>
        internal static string ErrorActualizarCarrito {
            get {
                return ResourceManager.GetString("ErrorActualizarCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al actualizar los datos del manga..
        /// </summary>
        internal static string ErrorActualizarManga {
            get {
                return ResourceManager.GetString("ErrorActualizarManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al intentar agregar un manga al carrito de compra..
        /// </summary>
        internal static string ErrorAgregarProductoCarrito {
            get {
                return ResourceManager.GetString("ErrorAgregarProductoCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido al asociar/crear el id del carrito de compra..
        /// </summary>
        internal static string ErrorAsociarIdCarrito {
            get {
                return ResourceManager.GetString("ErrorAsociarIdCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al borrar el manga.
        /// </summary>
        internal static string ErrorBorradoManga {
            get {
                return ResourceManager.GetString("ErrorBorradoManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al borrar el autor.
        /// </summary>
        internal static string ErrorBorrarAutor {
            get {
                return ResourceManager.GetString("ErrorBorrarAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al intentar quitar un manga del carrito de compra..
        /// </summary>
        internal static string ErrorBorrarProductoCarrito {
            get {
                return ResourceManager.GetString("ErrorBorrarProductoCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al calcular el total de pago del carrito de compra..
        /// </summary>
        internal static string ErrorCalcularTotalCarrito {
            get {
                return ResourceManager.GetString("ErrorCalcularTotalCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inesperado al intentar obtener el autor por id..
        /// </summary>
        internal static string ErrorConsultaAutor {
            get {
                return ResourceManager.GetString("ErrorConsultaAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intentar consultar los autores..
        /// </summary>
        internal static string ErrorConsultarTodosAutores {
            get {
                return ResourceManager.GetString("ErrorConsultarTodosAutores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al intentar consultar los carritos de compra..
        /// </summary>
        internal static string ErrorConsultarTodosCarritos {
            get {
                return ResourceManager.GetString("ErrorConsultarTodosCarritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al intentar convertir el tipo de dato..
        /// </summary>
        internal static string ErrorConversionDato {
            get {
                return ResourceManager.GetString("ErrorConversionDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al crear el autor..
        /// </summary>
        internal static string ErrorCreacionAutor {
            get {
                return ResourceManager.GetString("ErrorCreacionAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al crear el género..
        /// </summary>
        internal static string ErrorCreacionGenero {
            get {
                return ResourceManager.GetString("ErrorCreacionGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al crear el manga.
        /// </summary>
        internal static string ErrorCreacionManga {
            get {
                return ResourceManager.GetString("ErrorCreacionManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La imágen tiene que ser de formato gif, png, jpeg o jpg.
        /// </summary>
        internal static string ErrorFormatoArchivo {
            get {
                return ResourceManager.GetString("ErrorFormatoArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id del autor ingresado no existe.
        /// </summary>
        internal static string ErrorIdAutor {
            get {
                return ResourceManager.GetString("ErrorIdAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id del género ingresado no existe.
        /// </summary>
        internal static string ErrorIdGenero {
            get {
                return ResourceManager.GetString("ErrorIdGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El id ingresado no es correcto..
        /// </summary>
        internal static string ErrorIdIncorrecto {
            get {
                return ResourceManager.GetString("ErrorIdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id del manga ingresado no existe.
        /// </summary>
        internal static string ErrorIdManga {
            get {
                return ResourceManager.GetString("ErrorIdManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Código no puede ser nulo..
        /// </summary>
        internal static string ErrorIdNulo {
            get {
                return ResourceManager.GetString("ErrorIdNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor esperado no puede ser nulo..
        /// </summary>
        internal static string ErrorNulo {
            get {
                return ResourceManager.GetString("ErrorNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro enviado por query string no existe..
        /// </summary>
        internal static string ErrorQueryString {
            get {
                return ResourceManager.GetString("ErrorQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al intentar redireccionar a otra página..
        /// </summary>
        internal static string ErrorResponseRedirect {
            get {
                return ResourceManager.GetString("ErrorResponseRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al vaciar el carrito de compra..
        /// </summary>
        internal static string ErrorVaciarCarroCompra {
            get {
                return ResourceManager.GetString("ErrorVaciarCarroCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al intentar encontrar un ítem dentro de un vector..
        /// </summary>
        internal static string ErrorValorNoEncontradoVector {
            get {
                return ResourceManager.GetString("ErrorValorNoEncontradoVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen.
        /// </summary>
        internal static string lblAniadirImagen {
            get {
                return ResourceManager.GetString("lblAniadirImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string lblDescripcion {
            get {
                return ResourceManager.GetString("lblDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edad.
        /// </summary>
        internal static string lblEdad {
            get {
                return ResourceManager.GetString("lblEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string lblEmpresa {
            get {
                return ResourceManager.GetString("lblEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string lblId {
            get {
                return ResourceManager.GetString("lblId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Autor.
        /// </summary>
        internal static string lblNombreAutor {
            get {
                return ResourceManager.GetString("lblNombreAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Género.
        /// </summary>
        internal static string lblNombreGenero {
            get {
                return ResourceManager.GetString("lblNombreGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        internal static string lblPrecio {
            get {
                return ResourceManager.GetString("lblPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Volumen.
        /// </summary>
        internal static string lblVolumen {
            get {
                return ResourceManager.GetString("lblVolumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Por favor seleccione un autor.
        /// </summary>
        internal static string spanErrorAutor {
            get {
                return ResourceManager.GetString("spanErrorAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * La descripción del género es obligatoria.
        /// </summary>
        internal static string spanErrorDescripcionGenero {
            get {
                return ResourceManager.GetString("spanErrorDescripcionGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * La descripción del manga es obligatoria.
        /// </summary>
        internal static string spanErrorDescripcionManga {
            get {
                return ResourceManager.GetString("spanErrorDescripcionManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * La descripción de la empresa es obligatoria.
        /// </summary>
        internal static string spanErrorEmpresaAutor {
            get {
                return ResourceManager.GetString("spanErrorEmpresaAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato del campo Código es incorrecto.
        /// </summary>
        internal static string spanErrorFormatoId {
            get {
                return ResourceManager.GetString("spanErrorFormatoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * El formato del precio no es correcto.
        /// </summary>
        internal static string spanErrorFormatoPrecio {
            get {
                return ResourceManager.GetString("spanErrorFormatoPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Por favor seleccione un género.
        /// </summary>
        internal static string spanErrorGenero {
            get {
                return ResourceManager.GetString("spanErrorGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * El campo Id es obligatorio.
        /// </summary>
        internal static string spanErrorId {
            get {
                return ResourceManager.GetString("spanErrorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * El Nombre del autor es obligatorio.
        /// </summary>
        internal static string spanErrorNombreAutor {
            get {
                return ResourceManager.GetString("spanErrorNombreAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * El Nombre del genero es obligatorio.
        /// </summary>
        internal static string spanErrorNombreGenero {
            get {
                return ResourceManager.GetString("spanErrorNombreGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * El nombre del manga es obligatorio.
        /// </summary>
        internal static string spanErrorNombreManga {
            get {
                return ResourceManager.GetString("spanErrorNombreManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * La Imagen es obligatoria.
        /// </summary>
        internal static string spanErrorPathImagen {
            get {
                return ResourceManager.GetString("spanErrorPathImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * El precio del manga es obligatorio.
        /// </summary>
        internal static string spanErrorPrecio {
            get {
                return ResourceManager.GetString("spanErrorPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * El No. del volumen del manga es obligatoria.
        /// </summary>
        internal static string spanErrorVolumen {
            get {
                return ResourceManager.GetString("spanErrorVolumen", resourceCulture);
            }
        }
    }
}
