//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosMangaGods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosMangaGods() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RecursosMangaGods", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El autor se ha actualizado exitosamente.
        /// </summary>
        internal static string ConfirmacionActualizacionAutor {
            get {
                return ResourceManager.GetString("ConfirmacionActualizacionAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El autor se ha borrado exitosamente..
        /// </summary>
        internal static string ConfirmacionBorradoAutor {
            get {
                return ResourceManager.GetString("ConfirmacionBorradoAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El autor se ha creado exitosamente.
        /// </summary>
        internal static string ConfirmacionCreacionAutor {
            get {
                return ResourceManager.GetString("ConfirmacionCreacionAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El género de manga se ha creado exitosamente.
        /// </summary>
        internal static string ConfirmacionCreacionGenero {
            get {
                return ResourceManager.GetString("ConfirmacionCreacionGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al actualizar los datos del autor..
        /// </summary>
        internal static string ErrorActualizarAutor {
            get {
                return ResourceManager.GetString("ErrorActualizarAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al borrar el autor.
        /// </summary>
        internal static string ErrorBorrarAutor {
            get {
                return ResourceManager.GetString("ErrorBorrarAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al crear el autor..
        /// </summary>
        internal static string ErrorCreacionAutor {
            get {
                return ResourceManager.GetString("ErrorCreacionAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al crear el género..
        /// </summary>
        internal static string ErrorCreacionGenero {
            get {
                return ResourceManager.GetString("ErrorCreacionGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id del autor ingresado no existe.
        /// </summary>
        internal static string ErrorIdAutor {
            get {
                return ResourceManager.GetString("ErrorIdAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id del género ingresado no existe.
        /// </summary>
        internal static string ErrorIdGenero {
            get {
                return ResourceManager.GetString("ErrorIdGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string lblDescripcion {
            get {
                return ResourceManager.GetString("lblDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edad.
        /// </summary>
        internal static string lblEdad {
            get {
                return ResourceManager.GetString("lblEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string lblEmpresa {
            get {
                return ResourceManager.GetString("lblEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string lblId {
            get {
                return ResourceManager.GetString("lblId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Género.
        /// </summary>
        internal static string lblNombreGenero {
            get {
                return ResourceManager.GetString("lblNombreGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * El la descripción del género es obligatoria.
        /// </summary>
        internal static string spanErrorDescripcionGenero {
            get {
                return ResourceManager.GetString("spanErrorDescripcionGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * La descripción de la empresa es obligatoria.
        /// </summary>
        internal static string spanErrorEmpresaAutor {
            get {
                return ResourceManager.GetString("spanErrorEmpresaAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * El campo Id es obligatorio.
        /// </summary>
        internal static string spanErrorId {
            get {
                return ResourceManager.GetString("spanErrorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * El Nombre del autor es obligatorio.
        /// </summary>
        internal static string spanErrorNombreAutor {
            get {
                return ResourceManager.GetString("spanErrorNombreAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * El Nombre del genero es obligatorio.
        /// </summary>
        internal static string spanErrorNombreGenero {
            get {
                return ResourceManager.GetString("spanErrorNombreGenero", resourceCulture);
            }
        }
    }
}
